{{- if .Values.externalSecret.enabled }}
{{- $cfg := index .Values "flow-analyzer" }}
{{- $data := .Values.externalSecret.data }}
{{- if and $cfg.routeros.devices .Values.externalSecret.routerosPasswordKey }}
{{- $data = append $data (dict "secretKey" "ROUTEROS_PASSWORD" "remoteKey" .Values.externalSecret.routerosPasswordKey) }}
{{- end }}
{{- if and $cfg.geoip.url (contains "{license_key}" $cfg.geoip.url) .Values.externalSecret.maxmindLicenseKey }}
{{- $data = append $data (dict "secretKey" "MAXMIND_LICENSE_KEY" "remoteKey" .Values.externalSecret.maxmindLicenseKey) }}
{{- end }}
{{- if and $cfg.adguard.url .Values.externalSecret.adguardUserKey }}
{{- $data = append $data (dict "secretKey" "ADGUARD_USER" "remoteKey" .Values.externalSecret.adguardUserKey) }}
{{- $data = append $data (dict "secretKey" "ADGUARD_PASSWORD" "remoteKey" .Values.externalSecret.adguardPasswordKey) }}
{{- end }}
{{- if and $cfg.alerts.webhook.enabled .Values.externalSecret.alertWebhookUrlKey }}
{{- $data = append $data (dict "secretKey" "ALERT_WEBHOOK_URL" "remoteKey" .Values.externalSecret.alertWebhookUrlKey) }}
{{- $data = append $data (dict "secretKey" "ALERT_WEBHOOK_HEADERS" "remoteKey" .Values.externalSecret.alertWebhookHeadersKey) }}
{{- end }}
{{- if and $cfg.alerts.email.enabled .Values.externalSecret.alertSmtpUrlKey }}
{{- $data = append $data (dict "secretKey" "ALERT_SMTP_URL" "remoteKey" .Values.externalSecret.alertSmtpUrlKey) }}
{{- end }}
{{- if and $cfg.access.token .Values.externalSecret.adminTokenKey }}
{{- $data = append $data (dict "secretKey" "ADMIN_TOKEN" "remoteKey" .Values.externalSecret.adminTokenKey) }}
{{- end }}
{{- $_ := set .Values.externalSecret "data" $data }}
{{ include "common.externalsecret" . }}
{{- end }}
