{{- if .Values.externalSecret.enabled }}
{{- $cfg := index .Values "flow-analyzer" }}
{{- $data := .Values.externalSecret.data }}
{{- if and $cfg.routeros.devices .Values.externalSecret.routerosPasswordKey }}
{{- $data = append $data (dict "secretKey" "ROUTEROS_PASSWORD" "remoteKey" .Values.externalSecret.routerosPasswordKey) }}
{{- end }}
{{- if and $cfg.geoip.url (contains "{license_key}" $cfg.geoip.url) .Values.externalSecret.maxmindLicenseKey }}
{{- $data = append $data (dict "secretKey" "MAXMIND_LICENSE_KEY" "remoteKey" .Values.externalSecret.maxmindLicenseKey) }}
{{- end }}
{{- $_ := set .Values.externalSecret "data" $data }}
{{ include "common.externalsecret" . }}
{{- end }}
