---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flightaware
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: mlat-beast-output
      port: 31005
      targetPort: 31005
      protocol: TCP
  selector:
    app.kubernetes.io/controller: flightaware
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
