apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-opensky
  labels:
    kasten/backup: "true"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: opensky
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/controller: opensky
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      containers:
        - name: opensky
          env:
          - name: TZ
            value: {{ .Values.cluster.timezone }}
          {{- range $key, $value := .Values.pods.opensky.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          image: {{ .Values.pods.opensky.image.repository }}:{{ .Values.pods.opensky.image.tag }}
          imagePullPolicy: IfNotPresent
