apiVersion: v2
description: A Helm chart for Prowlarr
name: prowlarr
version: 1.0.1
appVersion: "2.1.5"
kubeVersion: ">=1.31.0-0"
home: https://prowlarr.com
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png
sources:
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/ullbergm/openshift
keywords:
  - prowlarr
  - indexer
  - media
  - usenet
  - torrent
annotations:
  charts.openshift.io/name: prowlarr
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: GPL-3.0-only

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
