cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Prowlarr
  group: Media
  icon: cbi:prowlarr
  iconColor: ""
  image: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png"
  description: "Indexer management"
  port: 9696
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/home-operations/prowlarr
      # renovate: datasource=docker depName=ghcr.io/home-operations/prowlarr versioning=semver
      tag: 2.1.5.5213@sha256:52b40a9147d4056d8c5edc535adddad32da282df4c3099321378e40dbfcf898a
      pullPolicy: IfNotPresent
