---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: {{ .Release.Name }}-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: synology-iscsi
          httpConnection:
            allowInsecure: true
            #host: {{ .Values.cluster.storage.democratic-csi.httpConnection.host }}
            #password: "{{ `{{ .NAS_PASSWORD }}` }}"
            #port: {{ .Values.cluster.storage.democratic-csi.httpConnection.port }}
            protocol: http
            serialize: true
            session: {{ .Values.cluster.name }}-democratic-csi
            username: "{{ `{{ .NAS_USERNAME }}` }}"
          iscsi:
            baseiqn: iqn.2000-01.com.synology:csi.
            interface: ""
            lunSnapshotTemplate:
              is_app_consistent: true
              is_locked: true
            lunTemplate:
              description: "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
              dev_attribs:
              - dev_attrib: emulate_tpws
                enable: 1
              - dev_attrib: emulate_caw
                enable: 1
              - dev_attrib: emulate_3pc
                enable: 1
              - dev_attrib: emulate_tpu
                enable: 1
              - dev_attrib: can_snapshot
                enable: 1
              type: BLUN
            namePrefix: {{ .Values.cluster.name }}-
            nameSuffix: ""
            #targetPortal: {{ .Values.cluster.storage.democratic-csi.iscsi.targetPortal }}
            targetPortals: []
            targetTemplate:
              auth_type: 0
              max_sessions: 0
  data:
    - remoteRef:
        key: NAS_PASSWORD
      secretKey: NAS_PASSWORD
    - remoteRef:
        key: NAS_USERNAME
      secretKey: NAS_USERNAME
