---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: {{ .Release.Name }}-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: synology-iscsi
          httpConnection:
            allowInsecure: true
  data:
    - remoteRef:
        key: NAS_PASSWORD
      secretKey: NAS_PASSWORD
    - remoteRef:
        key: NAS_USERNAME
      secretKey: NAS_USERNAME
