cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  #storage:
  #  config:
  #    storageClassName: synology-iscsi

application:
  name: LiteLLM
  group: AI/ML
  icon: subtitles
  iconColor: ""
  image: "https://raw.githubusercontent.com/BerriAI/litellm/refs/heads/main/docs/my-website/img/favicon.png"
  description: "Unified API to manage and deploy LLMs"
  port: 4000
  location: 0
  tags: admin

pods:
  main:
    image:
      repository: ghcr.io/berriai/litellm-non_root
      # renovate: datasource=docker depName=ghcr.io/berriai/litellm-non_root versioning=loose
      tag: main-v1.75.8-stable@sha256:eaa381bfd39b56c89e4a61be15ed87e7af02b65bd82a3f50d923e08a5f6d6027

  db:
    image:
      repository: postgres
      # renovate: datasource=docker depName=postgres versioning=docker
      tag: 17.7@sha256:2006493727bd5277eece187319af1ef82b4cf82cf4fc1ed00da0775b646ac2a4

  redis:
    image:
      repository: redis
      tag: "8-alpine@sha256:4eec4565e45aa0b3966554c866bc73211e281b0b3d89fe9a33c982e6faca809d"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
