{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha3" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha3
kind: Application
metadata:
  name: openshift-console
spec:
  name: OpenShift
  group: Infrastructure
  icon: simple-icons:redhatopenshift
  iconColor: "red"
  url: http://console-openshift-console.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}/dashboards
  info: OpenShift console
  location: 100
  tags: admin
{{- end }}
