apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    kasten/backup: "false"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: frontend
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/controller: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsUser: 0
        supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
      containers:
        - name: frontend
          env:
          - name: TZ
            value: {{ .Values.cluster.timezone }}
          - name: API_BASE_URL
            value: 'http://startpunkt-backend:8081'
          {{- range $key, $value := .Values.pods.frontend.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          image: {{ .Values.pods.frontend.image.repository }}:{{ .Values.pods.frontend.image.tag }}
          imagePullPolicy: {{ .Values.pods.frontend.image.pullPolicy }}
          volumeMounts:
          - mountPath: /work/application.yaml
            name: config
            subPath: application.yaml
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
