{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha3" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha3
kind: Application
metadata:
  name: github
spec:
  name: GitHub Repo
  group: Infrastructure
  icon: simple-icons:github
  url: {{ .Values.spec.source.repoURL }}
  info: GitHub Repo
  tags: admin
{{- end }}
