cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: ESPConnect
  group: Home Automation
  icon: mdi:chip
  image: "https://raw.githubusercontent.com/thelastoutpostworkshop/ESPConnect/refs/heads/main/public/favicon.ico"
  description: "ESP32 management tool"
  port: 8080

git:
  repository: https://github.com/thelastoutpostworkshop/ESPConnect.git
  # renovate: datasource=github-releases depName=thelastoutpostworkshop/ESPConnect
  ref: v1.0.5

pods:
  init:
    image:
      repository: docker.io/library/node
      tag: 20-alpine
  main:
    image:
      repository: docker.io/nginxinc/nginx-unprivileged
      tag: alpine
      pullPolicy: IfNotPresent
