{{- if .Values.zimUpdater.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-updater-script
data:
  update-zims.py: |
{{ .Files.Get "files/update-zims.py" | indent 4 }}
{{- end }}
