---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: {{ .Release.Namespace }}
            name: {{ .Values.externalSecrets.secret }}
          clientSecret:
            key: clientSecret
            namespace: {{ .Release.Namespace }}
            name: {{ .Values.externalSecrets.secret }}
      # Details to pull secrets from
      secretsScope:
        projectSlug: {{ .Values.externalSecrets.infisical.projectSlug }}
        environmentSlug: {{ .Values.externalSecrets.infisical.environmentSlug }}
        secretsPath: /
        recursive: true
      # optional
      hostAPI: https://app.infisical.com/api
