cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: MeTube
  group: Media
  icon: cbi:metube
  iconColor: ""
  image: ""
  description: "Download videos"
  port: 8081
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/alexta69/metube
      # renovate: datasource=docker depName=ghcr.io/alexta69/metube versioning=loose
      tag: 2026.02.08@sha256:e9871bd269a246927d01db7b1d84a92409211e49735a41bd59fee0d185f7d65c
      pullPolicy: IfNotPresent
    env:
      DOWNLOAD_DIR: /data/media/metube
      STATE_DIR: /config
