cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: MeTube
  group: Media
  icon: cbi:metube
  iconColor: ""
  image: ""
  description: "Download videos"
  port: 8081
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/alexta69/metube
      # renovate: datasource=docker depName=ghcr.io/alexta69/metube versioning=loose
      tag: 2026.04.12@sha256:9edc1efacf804f717febeac9f0c61c425cf6d83337048d3702225a0ebad40e4a
      pullPolicy: IfNotPresent
    env:
      DOWNLOAD_DIR: /data/media/metube
      STATE_DIR: /config
