cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: MeTube
  group: Media
  icon: cbi:metube
  iconColor: ""
  image: ""
  description: "Download videos"
  port: 8081
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/alexta69/metube
      # renovate: datasource=docker depName=ghcr.io/alexta69/metube versioning=loose
      tag: 2025.10.23@sha256:46be73330a37503772249bee27d03dd2c831ab3d135c932abbc448fcbe7e57a6
      pullPolicy: IfNotPresent
    env:
      DOWNLOAD_DIR: /data/media/metube
      STATE_DIR: /config
