---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/controller: db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
