---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediamtx
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9997
      targetPort: 9997
      protocol: TCP
    - name: rtsp
      port: 8554
      targetPort: 8554
      protocol: TCP
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
    - name: hls
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: srt
      port: 8890
      targetPort: 8890
      protocol: UDP
  selector:
    app.kubernetes.io/controller: mediamtx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
