---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
{{- if and .Values.neolink .Values.neolink.network .Values.neolink.network.ip }}
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: "keepalived-operator/lan"
{{- end }}
spec:
  type: ClusterIP
{{- if and .Values.neolink .Values.neolink.network .Values.neolink.network.ip }}
  externalIPs:
    - {{ .Values.neolink.network.ip }}
{{- end }}
  ports:
    - port: {{ .Values.application.port }}
      targetPort: rtsp
      protocol: TCP
      name: rtsp
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
