apiVersion: v2
description: A Helm chart for Flaresolverr
name: flaresolverr
version: 1.0.1
appVersion: "3.4.2"
kubeVersion: ">=1.31.0-0"
home: https://github.com/FlareSolverr/FlareSolverr
icon: https://avatars.githubusercontent.com/u/75936191?s=200&v=4
sources:
  - https://github.com/FlareSolverr/FlareSolverr
  - https://github.com/ullbergm/openshift
keywords:
  - flaresolverr
  - cloudflare
  - bypass
  - proxy
annotations:
  charts.openshift.io/name: flaresolverr
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: MIT

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
