{{- if (index .Values "synology-csi" "enabled") }}
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: synology-csi-scc
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostPorts: true
allowHostDirVolumePlugin: true
allowPrivilegeEscalation: true
allowedCapabilities:
- SYS_ADMIN
users:
- system:serviceaccount:synology-csi:synology-csi-controller
- system:serviceaccount:synology-csi:synology-csi-snapshotter
{{- end }}