---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "50-%s-disable-%s-interfaces" .Values.interface.role .Values.interface.disable }}
  labels:
    machineconfiguration.openshift.io/role: {{ .Values.interface.role }}
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            source: 'data:text/plain;base64,{{ printf "[main]\nplugins=keyfile\n\n[keyfile]\nunmanaged-devices=interface-name:%s*\n" .Values.interface.disable | b64enc }}'
          mode: 420
          overwrite: true
          path: /etc/NetworkManager/conf.d/{{ printf "50-%s-disable-%s-interfaces.conf" .Values.interface.role .Values.interface.disable }}
