apiVersion: v2
description: A Helm chart for Posterizarr
name: posterizarr
version: 1.0.1
appVersion: "1.9.99"
kubeVersion: ">=1.31.0-0"
home: https://github.com/fscorrupt/Posterizarr
icon: https://raw.githubusercontent.com/fscorrupt/Posterizarr/main/images/webhook.png
sources:
  - https://github.com/fscorrupt/Posterizarr
  - https://github.com/ullbergm/openshift
keywords:
  - posterizarr
  - posters
  - media
  - automation
annotations:
  charts.openshift.io/name: posterizarr
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: MIT

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
