cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Z-Wave
  group: Home Automation
  icon: cbi:zwavejs
  image: https://avatars.githubusercontent.com/u/54627315
  description: "Z-Wave integration"
  port: 8091
  tags: admin

pods:
  main:
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      # renovate: datasource=docker depName=ghcr.io/zwave-js/zwave-js-ui versioning=semver
      tag: 11.6.1@sha256:8cc2c1868129f9b8e3ffbd695b50668b845d8eb63e9c159b94cddca2e6d96e09
      pullPolicy: IfNotPresent
