cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Z-Wave
  group: Home Automation
  icon: cbi:zwavejs
  image: https://avatars.githubusercontent.com/u/54627315
  description: "Z-Wave integration"
  port: 8091
  tags: admin

pods:
  main:
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      # renovate: datasource=docker depName=ghcr.io/zwave-js/zwave-js-ui versioning=semver
      tag: 11.24.2@sha256:717f9d2609021b001d3543ec7144c4fc3ba0e31b61dbcd616383b93613b22f89
      pullPolicy: IfNotPresent
