cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Z-Wave
  group: Home Automation
  icon: cbi:zwavejs
  image: https://avatars.githubusercontent.com/u/54627315
  description: "Z-Wave integration"
  port: 8091
  tags: admin

pods:
  main:
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      # renovate: datasource=docker depName=ghcr.io/zwave-js/zwave-js-ui versioning=semver
      tag: 11.21.1@sha256:1193b96b31488e5a6c7895f16a27b2ead38f8a0c3d1bec335bb10b6d9f9e2905
      pullPolicy: IfNotPresent
