apiVersion: v2
description: A Helm chart for managing Keepalived in a Kubernetes cluster
name: keepalived
version: 1.0.0
kubeVersion: ">=1.31.0-0"

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
