cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Home Assistant
  group: Home Automation
  icon: mdi:home-assistant
  iconColor: skyblue
  image: https://upload.wikimedia.org/wikipedia/en/4/49/Home_Assistant_logo_%282023%29.svg
  description: "Home Automation"
  port: 8123
  location: 100

pods:
  main:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      # renovate: datasource=docker depName=ghcr.io/home-assistant/home-assistant versioning=semver
      tag: 2026.7.0@sha256:cb76c9922b530f6a5063a15463eb3ad6de287d297c826713abda16795bb98980
      pullPolicy: IfNotPresent

externalSecret:
  data:
    - NODE_RED_CREDENTIAL_SECRET
