cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

pods:
  main:
    image:
      repository: ghcr.io/squat/generic-device-plugin
      # renovate: datasource=docker depName=ghcr.io/squat/generic-device-plugin versioning=semver
      tag: latest@sha256:5acdaa40af84adf8b6f7bb1b8930d4e7be1ebe7f0109f00211ce3df43217b3b7
      pullPolicy: IfNotPresent
