cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

pods:
  main:
    image:
      repository: ghcr.io/squat/generic-device-plugin
      # renovate: datasource=docker depName=ghcr.io/squat/generic-device-plugin versioning=semver
      tag: latest@sha256:62dda74362cc607b00d1ade291c192ea894d8bdc53a969ed5328b866b2988597
      pullPolicy: IfNotPresent
