cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

pods:
  main:
    image:
      repository: ghcr.io/squat/generic-device-plugin
      # renovate: datasource=docker depName=ghcr.io/squat/generic-device-plugin versioning=semver
      tag: latest@sha256:c4e3a24a5f20449e027b9de2c3cee790169ab42220818315f5f8ee9830788981
      pullPolicy: IfNotPresent
