cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York

application:
  name: App
  group: Media
  icon: simple-icons:app
  iconColor: ""
  image: https://raw.githubusercontent.com/app/app/develop/Logo/400.png
  description: "A tool for managing stuff."
  port: 8080
  location: 0

storage:
  config:
    storageClassName: synology-iscsi
  media:
    nfs:
      server: nas
      path: /volume1/media

app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            #repository: ghcr.io/home-operations/app
            #tag: 1.0.0.0000
            pullPolicy: IfNotPresent
          env:
            TZ: America/New_York
            NODE_RED_CREDENTIAL_SECRET: secret

      serviceAccount:
        name: app-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 8080

  persistence:
    config:
      enabled: false
      existingClaim: app-config

    data:
      enabled: false
      existingClaim: app-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    labels:
      app: app
      version: 1.0.0.0000
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
