cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Bazarr
  group: Media
  icon: cbi:bazarr
  iconColor: ""
  image: "https://www.bazarr.media/assets/img/logo.png"
  description: "Manages subtitles"
  port: 6767
  location: 0

pods:
  main:
    image:
      # renovate custom-docker versioning=semver
      repository: ghcr.io/home-operations/bazarr
      tag: 1.5.3@sha256:2f1c32cb1420b2e56f60cfdf7823737eb501fdb2c13669429d23ab3a02e9ad90
      pullPolicy: IfNotPresent
