---
apiVersion: v1
kind: Service
metadata:
  name: emqx-dashboard
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: dashboard
  selector:
    apps.emqx.io/db-role: core
    app.kubernetes.io/instance: emqx
