apiVersion: v2
description: A Helm chart for the Cert Manager on OpenShift
name: cert-manager
version: 1.0.0
kubeVersion: ">=1.31.0-0"

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
