apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    kasten/backup: "true"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsUser: 0
        supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
      initContainers:
        - name: init-config
          image: {{ .Values.pods.init.image.repository }}:{{ .Values.pods.init.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:
            - "/app/config-file/init-config.sh"
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 128Mi
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /app/config-file
            name: config-files
      containers:
        - name: main
          env:
          - name: TZ
            value: {{ .Values.cluster.timezone }}
          {{- range $key, $value := .Values.pods.main.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          image: {{ .Values.pods.main.image.repository }}:{{ .Values.pods.main.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /app/config-file
            name: config-files
          - mountPath: /data
            name: data
        {{- if .Values.webhook.enabled }}
        - name: webhook
          image: {{ .Values.pods.main.image.repository }}:{{ .Values.pods.main.image.tag }}
          imagePullPolicy: IfNotPresent
          command: ["python3", "/app/config-file/webhook-server.py"]
          env:
          - name: TZ
            value: {{ .Values.cluster.timezone }}
          - name: WEBHOOK_PORT
            value: "{{ .Values.webhook.port }}"
          ports:
          - name: webhook
            containerPort: {{ .Values.webhook.port }}
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-files
              mountPath: /app/config-file
          readinessProbe:
            httpGet:
              path: /health
              port: webhook
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: webhook
            initialDelaySeconds: 15
            periodSeconds: 20
        {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: config-files
          configMap:
            name: {{ .Release.Name }}
            defaultMode: 0755
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-volume
