app-template:
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image
            repository: ghcr.io/ullbergm/startpunkt
            tag: 1.3.0
            pullPolicy: Always
          env:
            TZ: TIMEZONE
          probes:
            startup:
              enabled: true
            readiness:
              enabled: true
            liveness:
              enabled: true

      serviceAccount:
        name: startpunkt-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 8080

  defaultPodOptions:
    labels:
      app: startpunkt
      version: 1.0.0
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535

  persistence:
    config:
      enabled: true
      type: configMap
      name: startpunkt-config
      globalMounts:
        - path: /work/application.yaml
          subPath: application.yaml
          readOnly: true

startpunkt:
  # Default protocol for links if not specified in the resource
  defaultProtocol: "http"

  # Default language for the web UI
  defaultLanguage: "en-US"

  # Namespace selector determines which namespaces to look for resources in
  namespaceSelector:
    any: true  # If true, look for resources in all namespaces
    # matchNames:  # Uncomment and specify namespace names to limit the search to specific namespaces
    #   - default
    #   - startpunkt

  # Kubernetes integration, read ingress resources
  ingress:
    enabled: true  # If true, enable the reading of ingress resources
    onlyAnnotated: false  # Only consider resources with the annotation 'startpunkt.ullberg.us/enabled: "true"'

  # OpenShift integration, read OpenShift Routes
  openshift:
    enabled: true  # If true, enable the reading of OpenShift Route resources
    onlyAnnotated: false  # Only consider resources with the annotation 'startpunkt.ullberg.us/enabled: "true"'

  # Hajimari integration, read Hajimari Applications and Bookmarks
  hajimari:
    enabled: true  # If true, enable the reading of Hajimari Applications and Bookmarks

  # Istio Virtual Service integration, read Istio VirtualService resources
  istio:
    virtualservice:
      enabled: true  # If true, enable the reading of Hajimari Applications and Bookmarks
      onlyAnnotated: false  # Only consider resources with the annotation 'startpunkt.ullberg.us/enabled: "true"'

  # Web ui configuration
  web:
    title: "Startpunkt"  # Title of the web UI
    githubLink:
      enabled: true  # If true, enable the GitHub link in the web UI
    checkForUpdates: true  # If true, check for updates and show a notification in the web UI
    theme:
      light:
        bodyBgColor: "#F8F6F1"
        bodyColor: "#696969"
        emphasisColor: "#000000"
        textPrimaryColor: "#4C432E"
        textAccentColor: "#AA9A73"
      dark:
        bodyBgColor: "#232530"
        bodyColor: "#696969"
        emphasisColor: "#FAB795"
        textPrimaryColor: "#FAB795"
        textAccentColor: "#E95678"
