apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-nfd-
  name: openshift-nfd
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
  upgradeStrategy: Default
