{{- if eq (index .Values "custom-error-pages" "template") "l7" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: custom-error-code-pages
  name: custom-error-code-pages
  namespace: openshift-config
data:
  error-page-404.http: |
    HTTP/1.0 404 File Not Found
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="robots" content="nofollow,noarchive,noindex">
      <title>Not Found</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="404: Not Found">
      <meta name="description" content="The server can not find the requested page">
      <meta property="og:title" content="404: Not Found">
      <meta property="og:description" content="The server can not find the requested page">
      <meta property="twitter:title" content="404: Not Found">
      <meta property="twitter:description" content="The server can not find the requested page">
      <style>
        :root {
          --color-primary: #f7fafc;
          --color-inverted: #a0aec0;
        }
        @media (prefers-color-scheme: dark) {
          :root {
            --color-primary: #222526;
            --color-inverted: #fff;
          }
        }
        html, body {
          margin: 0;
          padding: 0;
          min-height: 100%;
          height: 100%;
          width: 100%;
          background-color: var(--color-primary);
          color: var(--color-inverted);
          font-family: sans-serif;
          font-size: 16px;
          word-break: keep-all;
        }
        @media screen and (min-width: 2000px) {
          html, body {
            font-size: 20px;
          }
        }
        body {
          display: flex;
          justify-content: center;
          align-items: center;
        }
        main {
          display: flex;
          flex-direction: column;
        }
        article {
          display: flex;
          align-items: center;
          justify-content: center;
        }
        article .code h1, article .desc p {
          font-size: 1.7em;
          margin: 0;
          padding: 0;
        }
        article .code {
          border-right: 2px solid;
          padding: 0.12em 0.7em;
          margin: 0;
          text-align: right;
        }
        article .code h1 {
          font-weight: normal;
        }
        article .desc {
          text-align: left;
          padding: 0.7em;
        }
        article .desc p {
          font-weight: lighter;
          text-transform: uppercase;
        }
      </style>
    </head>
    <body>
    <main>
      <article>
        <div class="code">
          <h1>404</h1>
        </div>
        <div class="desc">
          <p>Not Found</p>
        </div>
      </article>
    </main>
    </body>
    </html>

  error-page-503.http: |
    HTTP/1.0 503 Service Unavailable
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="robots" content="nofollow,noarchive,noindex">
      <title>Service Unavailable</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="refresh" content="30">
      <meta name="title" content="503: Service Unavailable">
      <meta name="description" content="The server is temporarily overloading or down">
      <meta property="og:title" content="503: Service Unavailable">
      <meta property="og:description" content="The server is temporarily overloading or down">
      <meta property="twitter:title" content="503: Service Unavailable">
      <meta property="twitter:description" content="The server is temporarily overloading or down">
      <style>
        :root {
          --color-primary: #f7fafc;
          --color-inverted: #a0aec0;
        }
        @media (prefers-color-scheme: dark) {
          :root {
            --color-primary: #222526;
            --color-inverted: #fff;
          }
        }
        html, body {
          margin: 0;
          padding: 0;
          min-height: 100%;
          height: 100%;
          width: 100%;
          background-color: var(--color-primary);
          color: var(--color-inverted);
          font-family: sans-serif;
          font-size: 16px;
          word-break: keep-all;
        }
        @media screen and (min-width: 2000px) {
          html, body {
            font-size: 20px;
          }
        }
        body {
          display: flex;
          justify-content: center;
          align-items: center;
        }
        main {
          display: flex;
          flex-direction: column;
        }
        article {
          display: flex;
          align-items: center;
          justify-content: center;
        }
        article .code h1, article .desc p {
          font-size: 1.7em;
          margin: 0;
          padding: 0;
        }
        article .code {
          border-right: 2px solid;
          padding: 0.12em 0.7em;
          margin: 0;
          text-align: right;
        }
        article .code h1 {
          font-weight: normal;
        }
        article .desc {
          text-align: left;
          padding: 0.7em;
        }
        article .desc p {
          font-weight: lighter;
          text-transform: uppercase;
        }
      </style>
    </head>
    <body>
    <main>
      <article>
        <div class="code">
          <h1>503</h1>
        </div>
        <div class="desc">
          <p>Service Unavailable</p>
        </div>
      </article>
    </main>
    </body>
    </html>

{{- end }}
