---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# No namespace specified

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - nfd.yaml
  - intel-dp-gpu-device.yaml
  - google-coral-device.yaml
  - nesdr-rtlamr-device.yaml
...