---
apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  operand:
    image: 'registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9@sha256:b2c67faebc94b5fea1c2df64e475d3ede1c0e3f58b5c711ebcd00a51b6069d97'
    servicePort: 12000
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "vendor"
...