---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-cert-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: apps-wildcard-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-{{ .Values.certificates.letsencrypt.issuer }}
  commonName: "apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
  dnsNames:
    - "apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
    - "*.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
