---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.cluster.admin_email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              key: accessKeyID
              name: {{ .Release.Name }}-secret
            region: {{ .Values.certificates.aws.region }}
            secretAccessKeySecretRef:
              key: secretAccessKey
              name: {{ .Release.Name }}-secret
        selector:
          dnsZones:
            - {{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
{{ if .Values.cloudflare.enabled }}
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: cloudflare-api-key
              name: {{ .Release.Name }}-secret
            email: {{ .Values.cluster.admin_email }}
        selector:
          dnsZones:
            - {{ .Values.cloudflare.top_level_domain }}
{{ end }}
