cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Readarr
  group: Media
  icon: book-open
  iconColor: ""
  image: "https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/400.png"
  description: "Manages your eBook library"
  port: 8787
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/pennydreadful/bookshelf
      # renovate: datasource=docker depName=ghcr.io/pennydreadful/bookshelf versioning=loose
      tag: hardcover-v0.4.20
      pullPolicy: IfNotPresent
