apiVersion: v2
description: A Helm chart for Gaps
name: gaps
version: 1.0.1
appVersion: "0.10.4"
kubeVersion: ">=1.31.0-0"
home: https://github.com/JasonHHouse/gaps
icon: https://raw.githubusercontent.com/JasonHHouse/gaps/master/images/Final-Black.png
sources:
  - https://github.com/JasonHHouse/gaps
  - https://github.com/ullbergm/openshift
keywords:
  - gaps
  - plex
  - movies
  - collections
annotations:
  charts.openshift.io/name: gaps
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: MIT

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
