apiVersion: v2
description: A Helm chart for Sabnzbd
name: sabnzbd
version: 1.0.1
appVersion: "4.5.5"
kubeVersion: ">=1.31.0-0"
home: https://sabnzbd.org
icon: https://avatars.githubusercontent.com/u/960698?s=200&v=4
sources:
  - https://github.com/sabnzbd/sabnzbd
  - https://github.com/ullbergm/openshift
keywords:
  - sabnzbd
  - usenet
  - downloader
  - media
  - nzb
annotations:
  charts.openshift.io/name: sabnzbd
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: GPL-2.0-or-later

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
