cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Cyberchef
  group: Productivity
  icon: mdi:chef-hat
  iconColor: ""
  image: ""
  description: "The cyber Swiss Army knife"
  port: 8080
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/gchq/cyberchef
      # renovate: datasource=docker depName=ghcr.io/gchq/cyberchef versioning=semver
      tag: 11.5.0@sha256:fa74354a9c5dd014c8dacee843eb9218fb13465d678d8b049e97bc26a69a1640
      pullPolicy: IfNotPresent
