apiVersion: v2
description: A Helm chart for Kapowarr
name: kapowarr
version: 1.0.1
appVersion: "1.2.0"
kubeVersion: ">=1.31.0-0"
home: https://casvt.github.io/Kapowarr
icon: https://casvt.github.io/Kapowarr/assets/img/favicon.svg
sources:
  - https://github.com/Casvt/Kapowarr
  - https://github.com/ullbergm/openshift
keywords:
  - kapowarr
  - comics
  - manga
  - media
annotations:
  charts.openshift.io/name: kapowarr
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: GPL-3.0-only

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
