apiVersion: v2
description: A Helm chart for disabling enp2s network interfaces on master nodes
name: disable-master-enp2s
version: 1.0.0
kubeVersion: ">=1.31.0-0"

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
