apiVersion: v2
description: A Helm chart for Tautulli
name: tautulli
version: 1.0.1
appVersion: "2.16.0"
kubeVersion: ">=1.31.0-0"
home: https://tautulli.com
icon: https://tautulli.com/images/logo.svg
sources:
  - https://github.com/Tautulli/Tautulli
  - https://github.com/ullbergm/openshift
keywords:
  - tautulli
  - plex
  - statistics
  - media
  - monitoring
annotations:
  charts.openshift.io/name: tautulli
  charts.openshift.io/provider: ullberg
  charts.openshift.io/providerType: community
  category: Media
  licenses: GPL-3.0-only

maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
