{{ if .Values.applications.kapowarr }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kapowarr
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kapowarr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media-application
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}
          
        - name: storage.media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: storage.media.nfs.path
          value: {{ .Values.media.nfs.path }}

        - name: application.name
          value: kapowarr
        - name: application.group
          value: Media
        - name: application.icon
          value: television-box
        - name: application.image
          value: 'https://raw.githubusercontent.com/Casvt/Kapowarr/refs/heads/development/docs/assets/img/favicon.svg'
        - name: application.description
          value: "Kapowarr is a software to build and manage a comic book library"
        - name: app-template.service.main.ports.http.port
          value: '5656'

        # renovate custom-docker versioning=loose
        - name: app-template.controllers.main.containers.main.image.repository
          value: mrcas/kapowarr
        - name: app-template.controllers.main.containers.main.image.tag
          value: v1.2.0
        - name: app-template.controllers.main.containers.main.image.pullPolicy
          value: IfNotPresent
        - name: app-template.controllers.main.containers.main.env.TZ
          value: America/New_York

        - name: app-template.controllers.main.serviceAccount.name
          value: kapowarr-sa
        - name: app-template.persistence.data.enabled
          value: "true"
        - name: app-template.persistence.data.existingClaim
          value: kapowarr-data-volume
        - name: app-template.persistence.config.enabled
          value: "true"
        - name: app-template.persistence.config.existingClaim
          value: kapowarr-config
        - name: app-template.persistence.config.globalMounts[0].path
          value: /app/db

        - name: app-template.defaultPodOptions.labels.app
          value: kapowarr
        - name: app-template.defaultPodOptions.labels.version
          value: v1.2.0

        - name: app-template.defaultPodOptions.securityContext.runAsUser
          value: "0"
        - name: app-template.defaultPodOptions.securityContext.runAsGroup
          value: "0"

  syncPolicy:
{{ if .Values.spec.syncPolicy.automated.enabled }}
    automated: {}
{{ end }}
    syncOptions:
      - CreateNamespace=true
{{ end }}