{{ if .Values.applications.kavita }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kavita
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media-application
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}
          
        - name: storage.media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: storage.media.nfs.path
          value: {{ .Values.media.nfs.path }}

        - name: application.name
          value: kavita
        - name: application.group
          value: Media
        - name: application.icon
          value: book
        - name: application.image
          value: 'https://raw.githubusercontent.com/Kareadita/Kavita/develop/Logo/kavita.svg'
        - name: application.description
          value: "Manga reader"
        - name: app-template.service.main.ports.http.port
          value: '5000'

        # renovate custom-docker versioning=semver
        - name: app-template.controllers.main.containers.main.image.repository
          value: jvmilazz0/kavita
        - name: app-template.controllers.main.containers.main.image.tag
          value: 0.8.7
        - name: app-template.controllers.main.containers.main.image.pullPolicy
          value: IfNotPresent
        - name: app-template.controllers.main.containers.main.env.TZ
          value: America/New_York

        - name: app-template.controllers.main.serviceAccount.name
          value: kavita-sa
        - name: app-template.persistence.data.enabled
          value: "true"
        - name: app-template.persistence.data.existingClaim
          value: kavita-data-volume
        - name: app-template.persistence.config.enabled
          value: "true"
        - name: app-template.persistence.config.existingClaim
          value: kavita-config
        - name: app-template.persistence.config.globalMounts[0].path
          value: /kavita/config

        - name: app-template.defaultPodOptions.labels.app
          value: kavita
        - name: app-template.defaultPodOptions.labels.version
          value: 0.8.1

  syncPolicy:
{{ if .Values.spec.syncPolicy.automated.enabled }}
    automated: {}
{{ end }}
    syncOptions:
      - CreateNamespace=true
{{ end }}