{{- if .Values.pods.minio.createBucket }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-minio-bucket
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/controller: minio-bucket
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: false
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: mc
          image: {{ .Values.pods.minio.mcImage.repository }}:{{ .Values.pods.minio.mcImage.tag }}
          imagePullPolicy: {{ .Values.pods.minio.mcImage.pullPolicy }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: MINIO_ROOT_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc alias set cloudtak-minio "http://{{ .Release.Name }}-minio:9000" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" &&
              mc mb --ignore-existing "cloudtak-minio/{{ .Values.pods.minio.bucket }}"
{{- end }}
