---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/k10-kasten-operator-rhmp.kasten-io: ''
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: k10-kasten-operator-rhmp
  namespace: kasten-io
spec:
  channel: stable
  installPlanApproval: Automatic
  name: k10-kasten-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: k10-kasten-operator-rhmp.v8.0.8
