cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Pinchflat
  group: Media
  icon: television-box
  iconColor: ""
  image: "https://raw.githubusercontent.com/kieraneglin/pinchflat/refs/heads/master/priv/static/images/icon-2024-03-20.png"
  description: "Your next YouTube media manager"
  port: 8945
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/kieraneglin/pinchflat
      # renovate: datasource=docker depName=ghcr.io/kieraneglin/pinchflat versioning=semver
      tag: v2025.6.6@sha256:4e975edf58f0861a5cbfe8fc6aac4851ff5a02dfc3f05ffeea4982e3084a5a4a
      pullPolicy: IfNotPresent
