cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Plex
  group: Media
  icon: cbi:plex
  iconColor: "orange"
  image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Plex_logo_2022.svg"
  description: "Manages your movie library"
  port: 32400
  location: 100

plex:
  network:
    ip: 192.168.1.10

pods:
  main:
    image:
      repository: lscr.io/linuxserver/plex
      # renovate: datasource=docker depName=lscr.io/linuxserver/plex versioning=semver
      tag: 1.42.2@sha256:b13c1a01150225d88085214dc3deabb41985fa5427766c0126c84780d156b9a9
  imagemaid:
    image:
      repository: docker.io/kometateam/imagemaid
      # renovate: datasource=docker depName=docker.io/kometateam/imagemaid versioning=semver
      tag: v1.1.1@sha256:fbec331b36c1473f8a9c4214f55e5b097860476c8a5274eb61a2b85df89e56cc
