---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: SECRET_ADMIN_EMAIL_PLACEHOLDER
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsZones:
          - SECRET_TLD_PLACEHOLDER
      dns01:
        route53:
          region: AWS_REGION_PLACEHOLDER
          hostedZoneID: AWS_HOSTED_ZONE_ID_PLACEHOLDER
          accessKeyID: AWS_ACCESS_KEY_ID_PLACEHOLDER
          secretAccessKeySecretRef:
            name: route53-access-key
            key: secretAccessKey
