{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha3" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha3
kind: Bookmark
metadata:
  name: amazon
spec:
  name: Amazon Video
  group: Entertainment
  icon: simple-icons:amazon
  url: https://www.amazon.com/gp/video/storefront/
  info: Streaming
{{- end }}
