{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha4" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha4
kind: Bookmark
metadata:
  name: chatgpt
spec:
  name: ChatGPT
  group: Development
  icon: simple-icons:chatbot
  url: https://chatgpt.com/
  info: AI chatbot for everyday use
{{- end }}
