{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha3" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha3
kind: Bookmark
metadata:
  name: netflix
spec:
  name: Netflix
  group: Entertainment
  icon: simple-icons:netflix
  url: https://netflix.com/
  info: Streaming
{{- end }}
