{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha3" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha3
kind: Application
metadata:
  name: valetudo
spec:
  name: Vacuum
  group: Home Automation
  icon: robot-vacuum
  url: http://valetudo.{{ .Values.cluster.top_level_domain }}
  info: Home automation
{{- end }}
