{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha3" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha3
kind: Bookmark
metadata:
  name: zoho
spec:
  name: ZoHo Mail
  group: Communication
  icon: mdi:mail
  url: https://mail.zoho.com/
  info: ZoHo E-Mail
  location: 100
{{- end }}
