name: Validate

on:
  workflow_dispatch:
  push:
    branches: ["renovate/**"]

permissions:
  contents: read

jobs:
  validate:
    name: Run repo validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Set up Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Show versions
        run: |
          helm version
          task --version

      - name: Run validation tasks
        run: |
          task validate:all
