name: Validate

on:
  workflow_dispatch:
  pull_request:
    branches: ["v2"]

permissions:
  contents: read

jobs:
  validate:
    name: Run repo validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Task
        uses: arduino/setup-task@v2

      - name: Show versions
        run: |
          helm version
          task --version

      - name: Run validation tasks
        run: |
          task validate:all
