name: Validate

on:
  workflow_dispatch:
  pull_request:
    branches: ["v2"]

permissions:
  contents: read

jobs:
  validate:
    name: Run repo validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Task
        uses: arduino/setup-task@v2

      - name: Show versions
        run: |
          helm version
          task --version

      - name: Run validation tasks
        run: |
          task validate:all
