---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              # renovate: docker-image versioning=loose
              repository: ghcr.io/onedr0p/plex
              tag: 1.32.7.7621-871adbd44
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}

    serviceAccount:
      name: plex-sa

    service:
      main:
        # type: LoadBalancer
        # loadBalancerIP: "192.168.64.41"
        ports:
          http:
            port: 32400
          dlna-udp:
            port: 1900
            protocol: UDP
          dlna-tcp:
            port: 32469
            protocol: TCP
          plex-companion:
            port: 3005
            protocol: TCP
          plex-roku:
            port: 8234
            protocol: TCP
          gdm-1:
            port: 32410
            protocol: UDP
          gdm-2:
            port: 32412
            protocol: UDP
          gdm3:
            port: 32413
            protocol: UDP
          gdm-4:
            port: 32414
            protocol: UDP
          bonjour:
            port: 5353
            protocol: UDP

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          hajimari.io/group: "Media"
          hajimari.io/info: "Manages your movie library"
          # kubernetes.io/ingress.class: nginx
          # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   location = / {
          #     if ($http_x_plex_device = ""){
          #       return 301 $scheme://$host/web/index.html;
          #     }
          #   }
          route.openshift.io/termination: "edge" 
        hosts:
          - host: &host "plex.apps.openshift.${SECRET_TLD}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - {}

    persistence:
      # config:
      #   enabled: true
      #   existingClaim: plex-config

      data:
        enabled: true
        existingClaim: data-volume
        globalMounts:
          - path: /data

      transcode:
        enabled: true
        accessMode: ["ReadWriteOnce"]
        type: emptyDir

    defaultPodOptions:
      securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"
          supplementalGroups:
            - 44
            - 109
            - 100
            - 65535
